sudo: false
language: node_js
node_js:
  - '8.12.0'
  - "18"
before_script:
  - sudo apt-get update -y
  - sudo apt-get install pandoc libghc-pandoc-prof
  - pandoc -s sample_sotsuron.docx -t markdown -o sample_sotsuron.md
  - npm init -y
  - npm install textlint --save-dev
  - npm install textlint-rule-preset-ja-technical-writing --save-dev
  - npm install npx --save-dev
script:
  - npx textlint --preset ja-technical-writing sample_sotsuron.md -f pretty-error
  - npm install
  - npm test
